{% set name = "pmdarima" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8d2a0c0cd3f7ec90825fa25a917b5f66073de58033511de015a9e76e4e3d8f7

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29,!=0.29.18,!=0.29.31
    - numpy {{ numpy }}
    - pip
    - python
    - packaging
    - meson-python >=0.15.0
    - numpy >=2.0.0
  run:
    - python
    - joblib >=0.11
    - cython >=0.29,!=0.29.18,!=0.29.31
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19
    - scikit-learn >=0.22
    - scipy >=1.13.0
    - statsmodels >=0.14.5
    - urllib3
    - setuptools >=42,!=50.0.0
    # Bundled with setuptools, but want to be explicit
    - packaging >=17.1

test:
  source_files:
    - pmdarima/tests
  imports:
    - pmdarima
  commands:
    - pip check
    - python -m pytest -v
  requires:
    - pip
    - pytest
    - matplotlib

about:
  home: https://github.com/alkaline-ml/pmdarima
  description: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities.
  dev_url: https://github.com/alkaline-ml/pmdarima
  doc_url: https://alkaline-ml.com/pmdarima/

extra:
  recipe-maintainers:
    - tomasvanpottelbergh
    - cdesouza21
    - bkreider
  skip-lints:
    - python_build_tool_in_run
    - cython_must_be_in_host
