{% set name = "pmdarima" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b87f9d9f5b7dc2ddbd053687c2264e26ac98fd4118e843c7e9bc3dd7343e5c1a

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29,!=0.29.18,!=0.29.31
    - numpy 1.21.2  # [py<310]
    - numpy 1.21.6  # [py310 and unix]
    - numpy 1.22.3  # [py310 and win]
    - numpy 1.23.2  # [py311]
    - numpy 1.26.0  # [py312]
    - scipy 1.3.2  # [py<=38]
    - scipy 1.5.3  # [py<=38 and aarch64]
    - scipy 1.5.4  # [py39]
    - scipy 1.7.2  # [py310]
    - scipy 1.9.3  # [py311]
    - scipy 1.11.2  # [py312]
    - statsmodels 0.13.2  # [py<=310]
    - statsmodels 0.13.3  # [py311]
    - statsmodels 0.14.0  # [py312]
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - joblib >=0.11
    - cython >=0.29,!=0.29.18,!=0.29.31
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19
    - scikit-learn >=0.22
    - scipy >=1.3.2
    - statsmodels >=0.13.2
    - urllib3
    - setuptools >=38.6.0,!=50.0.0
    # Bundled with setuptools, but want to be explicit
    # - packaging >=17.1

test:
  source_files:
    - pmdarima/tests
  imports:
    - pmdarima
  commands:
    - pip check
    - python -m pytest -v
  requires:
    - pip
    - pytest
    - matplotlib

about:
  home: https://github.com/alkaline-ml/pmdarima
  description: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities.
  dev_url: https://github.com/alkaline-ml/pmdarima
  doc_url: https://alkaline-ml.com/pmdarima/

extra:
  recipe-maintainers:
    - tomasvanpottelbergh
    - cdesouza21
    - bkreider
