{% set name = "pmdarima" %}
{% set version = "1.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 090a7e195e849059e6b7f9908d80539f63c0771d8f9c5da44472960f17fcc9fa

build:
  number: 0
  # Unsatisfiable dependencies on win32 with python 3.10
  skip: true  # [py<37 or (win32 and py==310)]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29,!=0.29.18
    # 2022/4/15: pmdarima 1.8.5 has a min required numpy >=1.19.3 https://github.com/alkaline-ml/pmdarima/blob/cafd5c79f1e5696c609716eca1514f0aaaf2d317/requirements.txt#L3
    # but Anaconda has 1.19.2 on unix platforms so we use 1.20 branch 
    - numpy   1.20  # [not (osx and arm64) and py<310]
    - numpy   1.21  # [(osx and arm64) and py<310]
    - numpy   1.21  # [py==310]
    - pip
    - python
    - setuptools
    - wheel
  run:
    - cython >=0.29,!=0.29.18
    - joblib >=0.11
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19
    - python
    - scikit-learn >=0.22
    - scipy >=1.3.2
    - setuptools >=38.6.0,!=50.0.0
    - statsmodels >=0.11,!=0.12.0
    - urllib3

test:
  source_files:
    - pmdarima/tests
  imports:
    - pmdarima
  commands:
    - pip check
    - python -m pytest -v
  requires:
    - pip
    - pytest
    - matplotlib

about:
  home: https://github.com/alkaline-ml/pmdarima
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities
  dev_url: https://github.com/alkaline-ml/pmdarima
  doc_url: https://alkaline-ml.com/pmdarima/

extra:
  recipe-maintainers:
    - tomasvanpottelbergh
    - cdesouza21
    - bkreider
