{% set name = "pmdarima" %}
{% set version = "2.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8d2a0c0cd3f7ec90825fa25a917b5f66073de58033511de015a9e76e4e3d8f7

build:
  number: 1
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    # meson-python: error: Could not find ninja version 1.8.2 or newer
    - ninja-base >=1.8.2
    - meson-python >=0.15.0
    - numpy {{ numpy }}
    - cython >=0.29,!=0.29.18,!=0.29.31
    - packaging
  run:
    - python
    - joblib >=0.11
    - cython >=0.29,!=0.29.18,!=0.29.31
    - numpy >=1.21.6
    - pandas >=0.19
    - scikit-learn >=0.22
    # https://github.com/alkaline-ml/pmdarima/issues/590
    # The 'force_all_finite' was renamed to 'ensure_all_finite' in scipy 1.16
    - scipy >=1.13.0,<1.16  # [py<314]
    - scipy >=1.13.0  # [py==314]
    - statsmodels >=0.14.5
    - urllib3
    - setuptools >=42,!=50.0.0
    - packaging >=17.1

# test fails because conf_ints[:, 0] is a read-only numpy array slice — assigning to it raises -> 
# ValueError: assignment destination is read-only. This is an upstream bug in pmdarima/pipeline.py:478
{% set deselect_tests = " --deselect=test_pipeline.py::test_pipeline_predict_inverse_transform" %}

test:
  imports:
    - pmdarima
  commands:
    - pip check
    - pytest --pyargs pmdarima.tests {{ deselect_tests }} 
  requires:
    - pip
    - pytest
    - matplotlib >=2.2.0

about:
  home: https://github.com/alkaline-ml/pmdarima
  description: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities.
  dev_url: https://github.com/alkaline-ml/pmdarima
  doc_url: https://alkaline-ml.com/pmdarima

extra:
  recipe-maintainers:
    - tomasvanpottelbergh
    - cdesouza21
    - bkreider
  skip-lints:
    - python_build_tool_in_run
    - cython_must_be_in_host
