{% set name = "pmdarima" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91acb3f7c12f3cfd6263efe323d3b8f94b58dcd242d68f11560a6c717001b01f

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29,!=0.29.18,!=0.29.31
    - numpy   1.21  # [py<311]
    - numpy   1.23  # [py==311]
    - pip
    - python
    - setuptools
    - wheel
  run:
    - cython >=0.29,!=0.29.18,!=0.29.31
    - joblib >=0.11
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19
    - python
    - scikit-learn >=0.22
    - scipy >=1.3.2
    - setuptools >=38.6.0,!=50.0.0
    - statsmodels >=0.13.2
    - urllib3

test:
  source_files:
    - pmdarima/tests
  imports:
    - pmdarima
  commands:
    - pip check
    - python -m pytest -v
  requires:
    - pip
    - pytest
    - matplotlib

about:
  home: https://github.com/alkaline-ml/pmdarima
  description: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pmdarima (originally pyramid-arima, for the anagram of 'py' + 'arima') is a statistical library designed to fill the void in Python's time series analysis capabilities.
  dev_url: https://github.com/alkaline-ml/pmdarima
  doc_url: https://alkaline-ml.com/pmdarima/

extra:
  recipe-maintainers:
    - tomasvanpottelbergh
    - cdesouza21
    - bkreider
